image: kkarczmarczyk/node-yarn:8.0

pages:
  script:
  - yarn config set cache-folder /root/yarn-cache
  - yarn config set registry https://registry.npm.taobao.org
  - yarn global add hexo-cli
  #- yarn config set https-proxy http://192.168.1.108:1080
  - yarn
  - hexo generate
  artifacts:
    paths:
    - public

  only:
  - master
